version: "3.9"

services:

  backend:
    build:
      context: ./backend-spring
      dockerfile: Dockerfile
    container_name: backend-spring
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    depends_on: []

  frontend:
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    container_name: frontend-angular
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    external: true