server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Arquivos estáticos
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy opcional para chamar backend diretamente (ex: /api)
    # Ajuste caso queira isto:
    #
    # location /api/ {
    #     proxy_pass http://backend:8080/;
    # }
}